### ISSUE TITLE
Форматирование yamljs

### ISSUE THREAD

**Issue by mbelsky** [MeFoDy/calendar-generator#3]
Привет,

yamljs оборачивает некоторые строки в кавычки. Например ссылки и время из объекта answers. Пруф: https://runkit.com/mbelsky/yamljs-quotes

Как я понял из [комментария](https://github.com/web-standards-ru/calendar/pull/536#issuecomment-616222045) @pepelsbey это не валидно для сборщика календаря. 

Бот отправляющий события в канал использует `yaml` для парсинга файлов. Вероятно, если использовать его, кавычек не будет. RunKit demo: https://runkit.com/mbelsky/5e9cc133c746e3001a982977

**Comment by pepelsbey** [comment]
Я пока не понимаю суть вопроса, вижу только серию утверждений :)

**Comment by mbelsky** [comment]
Тут действительно нет вопроса. Это скорее баг репорт, но, вероятно, слишком сумбурный. Попробую более формально.

## 🐛Bug Report

calendar-generator оборачивает поля name, time и link в кавычки

### Сценарий

```
? Название события Test Event
? Событие однодневное? Да
? День события (dd.mm.yyyy) 01.01.2020
? Время начала (hh:mm) 00:00
? Время окончания (hh:mm) 01:00
? Город Москва
? Ссылка на страничку события в Интернете https://test.com
? Событие пройдёт онлайн? Нет
```

### Ожидаемый результат

```
name: Test Event
date: 01.01.2020
time: 00:00-01:00
city: Москва
link: https://test.com
```

### Фактический результат

```
name: 'Test Event'
date: 01.01.2020
time: '00:00-01:00'
city: Москва
link: 'https://test.com'
```

**Comment by pepelsbey** [comment]
Вот, так понятнее :) В целом, кавычки — не проблема. Просто они в 90% случаев не нужны и поскольку до сих пор YAML-файлы заводили руками, мы их не требовали и вычищали, когда они появлялись без причины.

Учитывая, что этот инструмент пока только помогает заводить события руками, я бы попробовал убрать кавычки из вывода.

**Comment by MeFoDy** [comment]
Мне кажется, с кавычками никаких проблем нет здесь. md — это служебные файлы, их, кажется, никто не читает глазами, чтобы по ивентам двигаться.

Специально не убирал, чтобы кавычки были там, где может возникнуть проблема. Парсилка ямлов отлично понимает, что это строка, никаких проблем при генерации событий не было замечено. А вот если не поставить кавычку, например, может выстрелить в названии ивента, когда там какой-то спецсимвол появится в названии (любят современные ивенты добавлять такие «фишечки» почему-то).

Опять же, используется для генерации тот же пакет, что дальше используется для парсинга и генерации в ics-календарь. То есть совместимость на уровне используемых инструментов осталась. Как я понял [по коду библиотеки](https://github.com/jeremyfa/yaml.js/blob/develop/src/Escaper.coffee), там на всякий используется экранирование вообще всегда, когда служебные символы есть в строке.
